# Generated by Django 3.2.9 on 2022-02-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('suche', 'suche'), ('biete', 'biete')], default='suche', max_length=6),
        ),
    ]
