# Generated by Django 4.0.1 on 2022-02-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('Suche', 'Suche'), ('Biete', 'Biete')], default='Suche', max_length=6),
        ),
    ]
