# Generated by Django 4.0.1 on 2022-02-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='producttype',
            field=models.CharField(choices=[('Produkt', 'Produkt'), ('Dienstleistung', 'Dienstleistung')], default='Produkt', max_length=15),
        ),
    ]
