# Generated by Django 3.2.9 on 2022-02-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_producttype'),
        ('blog', '0005_images'),
    ]

    operations = [
    ]
