# Generated by Django 3.2.9 on 2022-02-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_merge_0005_blog_producttype_0005_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='post',
            new_name='blog',
        ),
    ]
