# Generated by Django 3.2.9 on 2022-02-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_blog_category'),
        ('blog', '0010_alter_images_image'),
    ]

    operations = [
    ]
